const { getDb } = require('../database/database');
const config = require('../config/client');
const { formatDate } = require('./helpers');

/**
 * Generates an HTML transcript for a ticket channel.
 * Reads all messages from the channel and builds a static HTML page.
 *
 * @param {import('discord.js').TextChannel} channel - The ticket channel.
 * @param {string} ticketId - Unique ticket identifier.
 * @returns {Promise<string>} - The full HTML content as a string.
 */
async function generateTranscript(channel, ticketId) {
  const messages = [];
  let lastId = null;

  // Fetch all messages in the channel (Discord limit: 100 per call, max 10000)
  while (true) {
    const options = { limit: 100 };
    if (lastId) options.before = lastId;

    const fetched = await channel.messages.fetch(options);
    if (fetched.size === 0) break;

    messages.push(...fetched.values());
    lastId = fetched.last().id;
  }

  // Reverse to chronological order
  messages.reverse();

  const messageHtml = messages
    .map((msg) => {
      const avatar = msg.author.displayAvatarURL({ extension: 'png', size: 32 });
      const time = formatDate(msg.createdAt);
      const content = msg.content
        ? escapeHtml(msg.content)
        : '';
      const attachments = msg.attachments
        .map((a) => `<a href="${a.url}" target="_blank">${escapeHtml(a.name)}</a>`)
        .join(', ');
      const embeds = msg.embeds
        .map(
          (e) =>
            `<div class="embed">${e.title ? `<b>${escapeHtml(e.title)}</b>` : ''}${
              e.description ? `<p>${escapeHtml(e.description)}</p>` : ''
            }</div>`
        )
        .join('');

      return `
        <div class="message">
          <img src="${avatar}" alt="avatar" class="avatar" />
          <div class="message-content">
            <span class="author">${escapeHtml(msg.author.tag)}</span>
            <span class="time">${time}</span>
            <div class="text">${content}</div>
            ${attachments ? `<div class="attachments">📎 ${attachments}</div>` : ''}
            ${embeds}
          </div>
        </div>`;
    })
    .join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Ticket Transcript - ${escapeHtml(ticketId)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #1a1a2e; color: #e0e0e0; padding: 20px; }
    .header { text-align: center; padding: 20px; background: #16213e; border-radius: 8px; margin-bottom: 20px; }
    .header h1 { color: #5865F2; font-size: 24px; }
    .header p { color: #a0a0b0; font-size: 14px; margin-top: 5px; }
    .message { display: flex; gap: 12px; padding: 12px; margin-bottom: 8px; background: #0f3460; border-radius: 6px; }
    .avatar { width: 32px; height: 32px; border-radius: 50%; flex-shrink: 0; }
    .message-content { flex: 1; }
    .author { color: #5865F2; font-weight: 600; font-size: 14px; }
    .time { color: #7878a0; font-size: 12px; margin-left: 8px; }
    .text { margin-top: 4px; font-size: 14px; line-height: 1.4; word-wrap: break-word; }
    .attachments { margin-top: 4px; font-size: 13px; color: #57F287; }
    .embed { margin-top: 6px; padding: 8px; background: #1a1a3e; border-left: 3px solid #5865F2; border-radius: 4px; font-size: 13px; }
    .footer { text-align: center; margin-top: 30px; color: #7878a0; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>📄 Ticket Transcript</h1>
    <p>Ticket ID: ${escapeHtml(ticketId)} | Channel: ${escapeHtml(channel.name)} | Total Messages: ${messages.length}</p>
  </div>
  ${messageHtml}
  <div class="footer">Transcript generated by ${escapeHtml(config.embed.footer.text)}</div>
</body>
</html>`;

  return html;
}

function escapeHtml(text) {
  if (!text) return '';
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

module.exports = { generateTranscript };
